# 人员修改
UPDATE dcms_employee_information SET Emp_name = '刘鹏超' , Emp_ltime = NULL WHERE Emp_id = 'Y0003';
UPDATE dcms_employee_information SET Emp_name = '李长荣' , Emp_ltime = NULL WHERE Emp_id = 'Y0005';
UPDATE dcms_employee_information SET Emp_name = '郝昭成' , Emp_ltime = NULL WHERE Emp_id = 'Y0006';
UPDATE dcms_employee_information SET Emp_name = '梁兆广' , Emp_ltime = NULL WHERE Emp_id = 'Y0007';
UPDATE dcms_employee_information SET Emp_name = '曾祥军' , Emp_ltime = NULL WHERE Emp_id = 'Y0009';
UPDATE dcms_employee_information SET Emp_name = '肖东' , Emp_ltime = NULL WHERE Emp_id = 'Y0010';
UPDATE dcms_employee_information SET Emp_name = '郑楠' , Emp_ltime = NULL WHERE Emp_id = 'Y0012';
UPDATE dcms_employee_information SET Emp_name = '郑海南' , Emp_ltime = NULL WHERE Emp_id = 'Y0013';
UPDATE dcms_employee_information SET Emp_name = '薛斌' , Emp_ltime = NULL WHERE Emp_id = 'Y0014';
UPDATE dcms_employee_information SET Emp_name = '郭治涛' , Emp_ltime = NULL WHERE Emp_id = 'Y0015';
UPDATE dcms_employee_information SET Emp_name = '刘志雄' , Emp_ltime = NULL WHERE Emp_id = 'Y1002';
UPDATE dcms_employee_information SET Emp_name = '李志立' , Emp_ltime = NULL WHERE Emp_id = 'Y1003';
UPDATE dcms_employee_information SET Emp_name = '秦祥祥' , Emp_ltime = NULL WHERE Emp_id = 'Y1004';
UPDATE dcms_employee_information SET Emp_name = '韦国壮' , Emp_ltime = NULL WHERE Emp_id = 'Y1005';
UPDATE dcms_employee_information SET Emp_name = '戴寿君' , Emp_ltime = NULL WHERE Emp_id = 'Y1006';
UPDATE dcms_employee_information SET Emp_name = '申金卫' , Emp_ltime = NULL WHERE Emp_id = 'Y1007';
UPDATE dcms_employee_information SET Emp_name = '韩锦宏' , Emp_ltime = NULL WHERE Emp_id = 'Y1008';
UPDATE dcms_employee_information SET Emp_name = '杨英亮' , Emp_ltime = NULL WHERE Emp_id = 'Y1009';
UPDATE dcms_employee_information SET Emp_name = '陈俊' , Emp_ltime = NULL WHERE Emp_id = 'Y1010';
UPDATE dcms_employee_information SET Emp_name = '王湛文' , Emp_ltime = NULL WHERE Emp_id = 'Y1011';
UPDATE dcms_employee_information SET Emp_name = '袁志伟' , Emp_ltime = NULL WHERE Emp_id = 'Y1012';
UPDATE dcms_employee_information SET Emp_name = '肖建中' , Emp_ltime = NULL WHERE Emp_id = 'Y1014';
UPDATE dcms_employee_information SET Emp_name = '谭永祥' , Emp_ltime = NULL WHERE Emp_id = 'Y1015';
UPDATE dcms_employee_information SET Emp_name = '赖学超' , Emp_ltime = NULL WHERE Emp_id = 'Y1016';
UPDATE dcms_employee_information SET Emp_name = '龚莉莉' , Emp_ltime = NULL WHERE Emp_id = 'Y1017';
UPDATE dcms_employee_information SET Emp_name = '李君霞' , Emp_ltime = NULL WHERE Emp_id = 'Y1018';
UPDATE dcms_employee_information SET Emp_name = '林志坤' , Emp_ltime = NULL WHERE Emp_id = 'Y1019';
UPDATE dcms_employee_information SET Emp_name = '韦万朕' , Emp_ltime = NULL WHERE Emp_id = 'Y1020';
UPDATE dcms_employee_information SET Emp_name = '杨海标' , Emp_ltime = NULL WHERE Emp_id = 'Y1021';
UPDATE dcms_employee_information SET Emp_name = '杨真' , Emp_ltime = NULL WHERE Emp_id = 'Y1022';
UPDATE dcms_employee_information SET Emp_name = '吴永艺' , Emp_ltime = NULL WHERE Emp_id = 'Y1023';
UPDATE dcms_employee_information SET Emp_name = '朱强' , Emp_ltime = NULL WHERE Emp_id = 'Y1024';
UPDATE dcms_employee_information SET Emp_name = '姜德广' , Emp_ltime = NULL WHERE Emp_id = 'Y1025';
UPDATE dcms_employee_information SET Emp_name = '张志杰' , Emp_ltime = NULL WHERE Emp_id = 'Y1026';
UPDATE dcms_employee_information SET Emp_name = '黄婷婷' , Emp_ltime = NULL WHERE Emp_id = 'Y1027';
UPDATE dcms_employee_information SET Emp_name = '唐彩云' , Emp_ltime = NULL WHERE Emp_id = 'Y1028';
UPDATE dcms_employee_information SET Emp_name = '杨玉文' , Emp_ltime = NULL WHERE Emp_id = 'Y1029';
UPDATE dcms_employee_information SET Emp_name = '贾勃勃' , Emp_ltime = NULL WHERE Emp_id = 'Y1030';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1007';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1005';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1010';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1012';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1004';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1003';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1006';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1009';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'J1008';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'Y1001';
UPDATE dcms_employee_information SET Emp_ltime = NULL WHERE Emp_id = 'Y1031';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1103';
DELETE FROM dcms_employee_information WHERE Emp_id = '1327';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1121';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W1001';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1012';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1117';
DELETE FROM dcms_employee_information WHERE Emp_id = '6622';
DELETE FROM dcms_employee_information WHERE Emp_id = '2373';
DELETE FROM dcms_employee_information WHERE Emp_id = '1433';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1061';
DELETE FROM dcms_employee_information WHERE Emp_id = '3322';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1040';
DELETE FROM dcms_employee_information WHERE Emp_id = '6631';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1130';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0042';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1125';
DELETE FROM dcms_employee_information WHERE Emp_id = '1432';
DELETE FROM dcms_employee_information WHERE Emp_id = 'F1001';
DELETE FROM dcms_employee_information WHERE Emp_id = '6923';
DELETE FROM dcms_employee_information WHERE Emp_id = '1263';
DELETE FROM dcms_employee_information WHERE Emp_id = '7921';
DELETE FROM dcms_employee_information WHERE Emp_id = '1383';
DELETE FROM dcms_employee_information WHERE Emp_id = '2345';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1118';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1108';
DELETE FROM dcms_employee_information WHERE Emp_id = 'J1011';
DELETE FROM dcms_employee_information WHERE Emp_id = '1757';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1048';
DELETE FROM dcms_employee_information WHERE Emp_id = '7856';
DELETE FROM dcms_employee_information WHERE Emp_id = '7953';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0070';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0003';
DELETE FROM dcms_employee_information WHERE Emp_id = '1570';
DELETE FROM dcms_employee_information WHERE Emp_id = '1676';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1111';
DELETE FROM dcms_employee_information WHERE Emp_id = '7907';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0193';
DELETE FROM dcms_employee_information WHERE Emp_id = '1227';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0004';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1036';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1020';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0027';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1120';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0119';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0024';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0013';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0007';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0038';
DELETE FROM dcms_employee_information WHERE Emp_id = 'z0012';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0035';
DELETE FROM dcms_employee_information WHERE Emp_id = 'Z5510';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0011';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0010';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0010';
DELETE FROM dcms_employee_information WHERE Emp_id = 'z00015';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0001';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1015';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0002';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0086';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0065';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1013';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1046';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1008';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0003';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0128';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0023';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0004';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1084';
DELETE FROM dcms_employee_information WHERE Emp_id = 'z5513';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0019';
DELETE FROM dcms_employee_information WHERE Emp_id = 'J1002';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0016';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1014';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0018';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0125';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0014';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0021';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0083';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0009';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1029';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1011';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1083';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0013';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1021';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0183';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1079';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0024';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0008';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0017';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1024';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0005';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0029';
DELETE FROM dcms_employee_information WHERE Emp_id = 'z0007';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0033';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0016';
DELETE FROM dcms_employee_information WHERE Emp_id = 'z0006';
DELETE FROM dcms_employee_information WHERE Emp_id = 'z0008';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0030';
DELETE FROM dcms_employee_information WHERE Emp_id = 'z5516';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1010';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0028';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0022';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1044';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1007';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0037';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0025';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0008';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1047';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1027';
DELETE FROM dcms_employee_information WHERE Emp_id = 'Z5506';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0020';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0005';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0174';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0015';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1140';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0036';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0009';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1102';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0112';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1051';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0034';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0012';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1116';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0031';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0107';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0014';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0032';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1050';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0040';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0012';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0026';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0006';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S0011';
DELETE FROM dcms_employee_information WHERE Emp_id = 'J1001';
DELETE FROM dcms_employee_information WHERE Emp_id = 'S1049';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0001';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0002';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0006';
DELETE FROM dcms_employee_information WHERE Emp_id = 'w0018';
DELETE FROM dcms_employee_information WHERE Emp_id = 'w0019';
DELETE FROM dcms_employee_information WHERE Emp_id = 'w0020';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0042';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0210';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0211';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0212';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0213';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0214';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0215';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0226';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0227';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0228';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0229';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0230';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0231';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0232';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0233';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0234';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0235';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0236';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W0238';
DELETE FROM dcms_employee_information WHERE Emp_id = 'W1008';
DELETE FROM dcms_employee_information WHERE Emp_id = 'WB001';
DELETE FROM dcms_employee_information WHERE Emp_id = 'Y0001';
DELETE FROM dcms_employee_information WHERE Emp_id = 'Y0002';
DELETE FROM dcms_employee_information WHERE Emp_id = 'Y0004';
DELETE FROM dcms_employee_information WHERE Emp_id = 'Y0008';
DELETE FROM dcms_employee_information WHERE Emp_id = 'Y1013';
UPDATE dcms_employee_information SET Emp_id = '6923' WHERE Emp_oa_no = 'NT20002131';
UPDATE dcms_employee_information SET Emp_id = '1757' WHERE Emp_oa_no = 'NT10002645';

# 新增外购人员单价
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0003', '25000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0005', '25000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0006', '20000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0007', '18000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0009', '22000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0010', '20000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0012', '20000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0013', '15000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0014', '20000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y0015', '15000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1001', '22000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1002', '22000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1003', '28000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1004', '15000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1005', '12000','2015-10-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1006', '22000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1007', '29000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1008', '35000','2017-02-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1009', '29000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1010', '28000','2015-12-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1011', '27000','2017-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1011', '22000','2015-12-01', '2016-12-01' );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1012', '21000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1014', '21000','2015-10-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1015', '25000','2015-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1016', '25000','2016-03-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1017', '13000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1018', '13000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1019', '13000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1020', '13000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1021', '13000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1022', '13000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1023', '13000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1024', '18000','2013-07-01', '2015-12-01' );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1024', '21000','2016-01-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1025', '20000','2016-07-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1026', '25000','2016-09-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1027', '20000','2016-11-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1028', '20000','2016-11-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1029', '20000','2016-11-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1030', '20000','2017-02-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1031', '23000','2017-04-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1039', '26000','2017-10-01', NULL );
INSERT INTO dcms_employee_outsourcing ( emp_id, os_price, os_begin_date, os_end_date ) VALUES ('Y1040', '26000','2017-10-01', NULL );

